-- ============================================================
-- PHAN HE 2 - File 09B: Demo phuc hoi bang audit + Flashback
-- Chay sau 01-08. Can bat row movement truoc khi FLASHBACK TABLE.
-- ============================================================

CONNECT BVADMIN/"BVAdmin@2025";

ALTER TABLE HSBA_DV ENABLE ROW MOVEMENT;

-- Tạo CHECKPOINT_LOG nếu chưa có. Dùng ALL_TABLES theo CURRENT_SCHEMA (đúng cả khi chạy bằng
-- BVADMIN trực tiếp lẫn khi setup.ps1 chạy bằng SYS + ALTER SESSION SET CURRENT_SCHEMA=BVADMIN),
-- và bắt ORA-00955 phòng trường hợp bảng đã được file 07 tạo.
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM   ALL_TABLES
    WHERE  TABLE_NAME = 'CHECKPOINT_LOG'
      AND  OWNER = SYS_CONTEXT('USERENV','CURRENT_SCHEMA');

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE CHECKPOINT_LOG (
                EVENT_NAME VARCHAR2(100) PRIMARY KEY,
                SCN        NUMBER NOT NULL,
                CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
            )
        ]';
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;  -- -955 = name already used → bỏ qua
END;
/

MERGE INTO CHECKPOINT_LOG c
USING (
    SELECT 'demo_before_delete_hsba_dv' AS event_name,
           DBMS_FLASHBACK.GET_SYSTEM_CHANGE_NUMBER AS scn
    FROM dual
) s
ON (c.EVENT_NAME = s.EVENT_NAME)
WHEN MATCHED THEN
    UPDATE SET c.SCN = s.SCN, c.CREATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (EVENT_NAME, SCN) VALUES (s.EVENT_NAME, s.SCN);
COMMIT;

PROMPT === Trang thai truoc su co ===
SELECT COUNT(*) AS HSBA_DV_COUNT FROM HSBA_DV;
SELECT MAHSBA, LOAIDV, NGAYDV, MAKTV
FROM HSBA_DV
WHERE MAHSBA = 'HS001'
ORDER BY NGAYDV, LOAIDV;

PROMPT === Gia lap xoa nham dich vu cua HS001 ===
DELETE FROM HSBA_DV WHERE MAHSBA = 'HS001';
COMMIT;

SELECT COUNT(*) AS HSBA_DV_COUNT_AFTER_DELETE FROM HSBA_DV;

PROMPT === Audit/FGA gan nhat lien quan HSBA_DV ===
CONNECT SYSTEM/oracle;
SELECT DB_USER, OBJECT_SCHEMA, OBJECT_NAME, POLICY_NAME,
       SQL_TEXT, EXTENDED_TIMESTAMP
FROM DBA_FGA_AUDIT_TRAIL
WHERE OBJECT_SCHEMA = 'BVADMIN'
  AND OBJECT_NAME = 'HSBA_DV'
ORDER BY EXTENDED_TIMESTAMP DESC FETCH FIRST 5 ROWS ONLY;

PROMPT === Lay SCN checkpoint va phuc hoi bang HSBA_DV ===
CONNECT BVADMIN/"BVAdmin@2025";

SELECT EVENT_NAME, SCN, CREATED_AT
FROM CHECKPOINT_LOG
WHERE EVENT_NAME = 'demo_before_delete_hsba_dv';

DECLARE
    v_scn NUMBER;
BEGIN
    SELECT SCN INTO v_scn
    FROM CHECKPOINT_LOG
    WHERE EVENT_NAME = 'demo_before_delete_hsba_dv';

    EXECUTE IMMEDIATE 'FLASHBACK TABLE HSBA_DV TO SCN ' || v_scn;
END;
/

PROMPT === Verify sau phuc hoi ===
SELECT COUNT(*) AS HSBA_DV_COUNT_AFTER_FLASHBACK FROM HSBA_DV;
SELECT MAHSBA, LOAIDV, NGAYDV, MAKTV
FROM HSBA_DV
WHERE MAHSBA = 'HS001'
ORDER BY NGAYDV, LOAIDV;

PROMPT === Demo Flashback Query cho DONTHUOC ===
SELECT MAHSBA, NGAYDT, TENTHUOC, LIEUDUNG
FROM DONTHUOC AS OF TIMESTAMP (SYSTIMESTAMP - INTERVAL '5' MINUTE)
WHERE MAHSBA = 'HS001'
ORDER BY NGAYDT, TENTHUOC;

SELECT VERSIONS_STARTTIME, VERSIONS_OPERATION, MAHSBA, TENTHUOC, LIEUDUNG
FROM DONTHUOC VERSIONS BETWEEN TIMESTAMP MINVALUE AND MAXVALUE
WHERE MAHSBA = 'HS001'
ORDER BY VERSIONS_STARTTIME DESC NULLS LAST;
