<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>HospitalApp</AssemblyName>
    <RootNamespace>HospitalApp</RootNamespace>
    <ApplicationIcon>hospital.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.4.0" />
  </ItemGroup>

  <!-- Embed font Montserrat (đặt các file .ttf vào Resources/Fonts/) -->
  <ItemGroup>
    <EmbeddedResource Include="Resources/Fonts/*.ttf" />
  </ItemGroup>
</Project>
